/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * EndBox API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Register with password only, get auto-generated user ID
 */
export const registerBodyPasswordMin = 6;



export const RegisterBody = zod.object({
  "password": zod.string().min(registerBodyPasswordMin),
  "encryptedPrivateKey": zod.string().optional().describe('Client-side password-encrypted private key (base64)'),
  "publicKey": zod.string().optional().describe('ECDH public key (base64)')
})


/**
 * @summary Login with user ID and password
 */
export const LoginBody = zod.object({
  "userId": zod.string(),
  "password": zod.string()
})

export const loginResponseUserThemeDefault = `dark`;

export const LoginResponse = zod.object({
  "token": zod.string(),
  "user": zod.object({
  "id": zod.string(),
  "userId": zod.string().describe('Human-readable ID like END-48291'),
  "avatarUrl": zod.string().nullish(),
  "theme": zod.enum(['dark', 'light']).default(loginResponseUserThemeDefault),
  "storageUsedBytes": zod.number().optional(),
  "createdAt": zod.string()
}),
  "encryptedPrivateKey": zod.string().nullish().describe('Password-encrypted private key blob returned on login')
})


/**
 * @summary Get current authenticated user
 */
export const getMeResponseThemeDefault = `dark`;

export const GetMeResponse = zod.object({
  "id": zod.string(),
  "userId": zod.string().describe('Human-readable ID like END-48291'),
  "avatarUrl": zod.string().nullish(),
  "theme": zod.enum(['dark', 'light']).default(getMeResponseThemeDefault),
  "storageUsedBytes": zod.number().optional(),
  "createdAt": zod.string()
})


/**
 * @summary Search for a user by their exact user ID
 */
export const GetUserByIdParams = zod.object({
  "userId": zod.coerce.string()
})

export const GetUserByIdResponse = zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
})


/**
 * @summary Store or update user public key
 */
export const StorePublicKeyBody = zod.object({
  "publicKey": zod.string().describe('ECDH public key in base64'),
  "encryptedPrivateKey": zod.string().optional().describe('AES-GCM encrypted private key in base64')
})

export const StorePublicKeyResponse = zod.object({
  "userId": zod.string(),
  "publicKey": zod.string(),
  "encryptedPrivateKey": zod.string().nullish()
})


/**
 * @summary Get public key for a user
 */
export const GetPublicKeyParams = zod.object({
  "userId": zod.coerce.string()
})

export const GetPublicKeyResponse = zod.object({
  "userId": zod.string(),
  "publicKey": zod.string(),
  "encryptedPrivateKey": zod.string().nullish()
})


/**
 * @summary List all sent and received chat requests
 */
export const ListRequestsResponse = zod.object({
  "sent": zod.array(zod.object({
  "id": zod.string(),
  "fromUserId": zod.string(),
  "fromUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}).optional(),
  "toUserId": zod.string(),
  "toUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}).optional(),
  "status": zod.enum(['pending', 'accepted', 'declined', 'cancelled']),
  "createdAt": zod.string()
})),
  "received": zod.array(zod.object({
  "id": zod.string(),
  "fromUserId": zod.string(),
  "fromUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}).optional(),
  "toUserId": zod.string(),
  "toUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}).optional(),
  "status": zod.enum(['pending', 'accepted', 'declined', 'cancelled']),
  "createdAt": zod.string()
}))
})


/**
 * @summary Send a chat request to a user
 */
export const SendRequestBody = zod.object({
  "targetUserId": zod.string().describe('The user ID (e.g. END-48291) to send a request to')
})


/**
 * @summary Accept or decline a chat request
 */
export const UpdateRequestParams = zod.object({
  "requestId": zod.coerce.string()
})

export const UpdateRequestBody = zod.object({
  "action": zod.enum(['accept', 'decline'])
})

export const UpdateRequestResponse = zod.object({
  "id": zod.string(),
  "fromUserId": zod.string(),
  "fromUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}).optional(),
  "toUserId": zod.string(),
  "toUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}).optional(),
  "status": zod.enum(['pending', 'accepted', 'declined', 'cancelled']),
  "createdAt": zod.string()
})


/**
 * @summary Cancel a sent request
 */
export const CancelRequestParams = zod.object({
  "requestId": zod.coerce.string()
})


/**
 * @summary List all conversations for the current user
 */
export const listConversationsResponseLastMessageIsEditedDefault = false;
export const listConversationsResponseLastMessageIsDeletedDefault = false;
export const listConversationsResponseLastMessageIsReadDefault = false;
export const listConversationsResponseUnreadCountDefault = 0;
export const listConversationsResponseIsPinnedDefault = false;
export const listConversationsResponseIsMutedDefault = false;
export const listConversationsResponseIsArchivedDefault = false;
export const listConversationsResponseIsBlockedDefault = false;
export const listConversationsResponseOtherUserOnlineDefault = false;

export const ListConversationsResponseItem = zod.object({
  "id": zod.string(),
  "otherUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}),
  "lastMessage": zod.object({
  "id": zod.string(),
  "conversationId": zod.string(),
  "senderId": zod.string(),
  "type": zod.enum(['text', 'image', 'file', 'voice', 'video', 'pdf', 'zip']),
  "encryptedContent": zod.string().nullish().describe('AES-GCM encrypted message content (base64)'),
  "iv": zod.string().nullish().describe('Initialization vector for decryption (base64)'),
  "attachmentUrl": zod.string().nullish(),
  "attachmentName": zod.string().nullish(),
  "attachmentSize": zod.number().nullish(),
  "replyToId": zod.string().nullish(),
  "replyTo": zod.unknown().optional(),
  "isEdited": zod.boolean().default(listConversationsResponseLastMessageIsEditedDefault),
  "isDeleted": zod.boolean().default(listConversationsResponseLastMessageIsDeletedDefault),
  "isRead": zod.boolean().default(listConversationsResponseLastMessageIsReadDefault),
  "createdAt": zod.string(),
  "editedAt": zod.string().nullish()
}).optional(),
  "unreadCount": zod.number().default(listConversationsResponseUnreadCountDefault),
  "isPinned": zod.boolean().default(listConversationsResponseIsPinnedDefault),
  "isMuted": zod.boolean().default(listConversationsResponseIsMutedDefault),
  "isArchived": zod.boolean().default(listConversationsResponseIsArchivedDefault),
  "isBlocked": zod.boolean().default(listConversationsResponseIsBlockedDefault),
  "otherUserOnline": zod.boolean().default(listConversationsResponseOtherUserOnlineDefault),
  "createdAt": zod.string()
})
export const ListConversationsResponse = zod.array(ListConversationsResponseItem)


/**
 * @summary Get conversation stats (total, unread, pinned)
 */
export const GetConversationStatsResponse = zod.object({
  "total": zod.number(),
  "unread": zod.number(),
  "pinned": zod.number(),
  "archived": zod.number()
})


/**
 * @summary Get a single conversation
 */
export const GetConversationParams = zod.object({
  "conversationId": zod.coerce.string()
})

export const getConversationResponseLastMessageIsEditedDefault = false;
export const getConversationResponseLastMessageIsDeletedDefault = false;
export const getConversationResponseLastMessageIsReadDefault = false;
export const getConversationResponseUnreadCountDefault = 0;
export const getConversationResponseIsPinnedDefault = false;
export const getConversationResponseIsMutedDefault = false;
export const getConversationResponseIsArchivedDefault = false;
export const getConversationResponseIsBlockedDefault = false;
export const getConversationResponseOtherUserOnlineDefault = false;

export const GetConversationResponse = zod.object({
  "id": zod.string(),
  "otherUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}),
  "lastMessage": zod.object({
  "id": zod.string(),
  "conversationId": zod.string(),
  "senderId": zod.string(),
  "type": zod.enum(['text', 'image', 'file', 'voice', 'video', 'pdf', 'zip']),
  "encryptedContent": zod.string().nullish().describe('AES-GCM encrypted message content (base64)'),
  "iv": zod.string().nullish().describe('Initialization vector for decryption (base64)'),
  "attachmentUrl": zod.string().nullish(),
  "attachmentName": zod.string().nullish(),
  "attachmentSize": zod.number().nullish(),
  "replyToId": zod.string().nullish(),
  "replyTo": zod.unknown().optional(),
  "isEdited": zod.boolean().default(getConversationResponseLastMessageIsEditedDefault),
  "isDeleted": zod.boolean().default(getConversationResponseLastMessageIsDeletedDefault),
  "isRead": zod.boolean().default(getConversationResponseLastMessageIsReadDefault),
  "createdAt": zod.string(),
  "editedAt": zod.string().nullish()
}).optional(),
  "unreadCount": zod.number().default(getConversationResponseUnreadCountDefault),
  "isPinned": zod.boolean().default(getConversationResponseIsPinnedDefault),
  "isMuted": zod.boolean().default(getConversationResponseIsMutedDefault),
  "isArchived": zod.boolean().default(getConversationResponseIsArchivedDefault),
  "isBlocked": zod.boolean().default(getConversationResponseIsBlockedDefault),
  "otherUserOnline": zod.boolean().default(getConversationResponseOtherUserOnlineDefault),
  "createdAt": zod.string()
})


/**
 * @summary Update conversation settings (pin, mute, archive, block)
 */
export const UpdateConversationParams = zod.object({
  "conversationId": zod.coerce.string()
})

export const UpdateConversationBody = zod.object({
  "isPinned": zod.boolean().optional(),
  "isMuted": zod.boolean().optional(),
  "isArchived": zod.boolean().optional(),
  "isBlocked": zod.boolean().optional()
})

export const updateConversationResponseLastMessageIsEditedDefault = false;
export const updateConversationResponseLastMessageIsDeletedDefault = false;
export const updateConversationResponseLastMessageIsReadDefault = false;
export const updateConversationResponseUnreadCountDefault = 0;
export const updateConversationResponseIsPinnedDefault = false;
export const updateConversationResponseIsMutedDefault = false;
export const updateConversationResponseIsArchivedDefault = false;
export const updateConversationResponseIsBlockedDefault = false;
export const updateConversationResponseOtherUserOnlineDefault = false;

export const UpdateConversationResponse = zod.object({
  "id": zod.string(),
  "otherUser": zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "avatarUrl": zod.string().nullish()
}),
  "lastMessage": zod.object({
  "id": zod.string(),
  "conversationId": zod.string(),
  "senderId": zod.string(),
  "type": zod.enum(['text', 'image', 'file', 'voice', 'video', 'pdf', 'zip']),
  "encryptedContent": zod.string().nullish().describe('AES-GCM encrypted message content (base64)'),
  "iv": zod.string().nullish().describe('Initialization vector for decryption (base64)'),
  "attachmentUrl": zod.string().nullish(),
  "attachmentName": zod.string().nullish(),
  "attachmentSize": zod.number().nullish(),
  "replyToId": zod.string().nullish(),
  "replyTo": zod.unknown().optional(),
  "isEdited": zod.boolean().default(updateConversationResponseLastMessageIsEditedDefault),
  "isDeleted": zod.boolean().default(updateConversationResponseLastMessageIsDeletedDefault),
  "isRead": zod.boolean().default(updateConversationResponseLastMessageIsReadDefault),
  "createdAt": zod.string(),
  "editedAt": zod.string().nullish()
}).optional(),
  "unreadCount": zod.number().default(updateConversationResponseUnreadCountDefault),
  "isPinned": zod.boolean().default(updateConversationResponseIsPinnedDefault),
  "isMuted": zod.boolean().default(updateConversationResponseIsMutedDefault),
  "isArchived": zod.boolean().default(updateConversationResponseIsArchivedDefault),
  "isBlocked": zod.boolean().default(updateConversationResponseIsBlockedDefault),
  "otherUserOnline": zod.boolean().default(updateConversationResponseOtherUserOnlineDefault),
  "createdAt": zod.string()
})


/**
 * @summary Clear chat or delete conversation
 */
export const ClearConversationParams = zod.object({
  "conversationId": zod.coerce.string()
})


/**
 * @summary List latest messages in a conversation
 */
export const GetMessagesParams = zod.object({
  "conversationId": zod.coerce.string()
})

export const getMessagesResponseMessagesItemIsEditedDefault = false;
export const getMessagesResponseMessagesItemIsDeletedDefault = false;
export const getMessagesResponseMessagesItemIsReadDefault = false;

export const GetMessagesResponse = zod.object({
  "messages": zod.array(zod.object({
  "id": zod.string(),
  "conversationId": zod.string(),
  "senderId": zod.string(),
  "type": zod.enum(['text', 'image', 'file', 'voice', 'video', 'pdf', 'zip']),
  "encryptedContent": zod.string().nullish().describe('AES-GCM encrypted message content (base64)'),
  "iv": zod.string().nullish().describe('Initialization vector for decryption (base64)'),
  "attachmentUrl": zod.string().nullish(),
  "attachmentName": zod.string().nullish(),
  "attachmentSize": zod.number().nullish(),
  "replyToId": zod.string().nullish(),
  "replyTo": zod.unknown().optional(),
  "isEdited": zod.boolean().default(getMessagesResponseMessagesItemIsEditedDefault),
  "isDeleted": zod.boolean().default(getMessagesResponseMessagesItemIsDeletedDefault),
  "isRead": zod.boolean().default(getMessagesResponseMessagesItemIsReadDefault),
  "createdAt": zod.string(),
  "editedAt": zod.string().nullish()
})),
  "hasMore": zod.boolean(),
  "nextCursor": zod.string().nullish()
})


/**
 * @summary Send an encrypted message
 */
export const SendMessageParams = zod.object({
  "conversationId": zod.coerce.string()
})

export const SendMessageBody = zod.object({
  "type": zod.enum(['text', 'image', 'file', 'voice', 'video', 'pdf', 'zip']),
  "encryptedContent": zod.string().optional().describe('AES-GCM encrypted content (base64)'),
  "iv": zod.string().optional().describe('Initialization vector (base64)'),
  "attachmentUrl": zod.string().optional(),
  "attachmentName": zod.string().optional(),
  "attachmentSize": zod.number().optional(),
  "replyToId": zod.string().optional()
})


/**
 * @summary Edit a message
 */
export const EditMessageParams = zod.object({
  "conversationId": zod.coerce.string(),
  "messageId": zod.coerce.string()
})

export const EditMessageBody = zod.object({
  "encryptedContent": zod.string(),
  "iv": zod.string()
})

export const editMessageResponseIsEditedDefault = false;
export const editMessageResponseIsDeletedDefault = false;
export const editMessageResponseIsReadDefault = false;

export const EditMessageResponse = zod.object({
  "id": zod.string(),
  "conversationId": zod.string(),
  "senderId": zod.string(),
  "type": zod.enum(['text', 'image', 'file', 'voice', 'video', 'pdf', 'zip']),
  "encryptedContent": zod.string().nullish().describe('AES-GCM encrypted message content (base64)'),
  "iv": zod.string().nullish().describe('Initialization vector for decryption (base64)'),
  "attachmentUrl": zod.string().nullish(),
  "attachmentName": zod.string().nullish(),
  "attachmentSize": zod.number().nullish(),
  "replyToId": zod.string().nullish(),
  "replyTo": zod.unknown().optional(),
  "isEdited": zod.boolean().default(editMessageResponseIsEditedDefault),
  "isDeleted": zod.boolean().default(editMessageResponseIsDeletedDefault),
  "isRead": zod.boolean().default(editMessageResponseIsReadDefault),
  "createdAt": zod.string(),
  "editedAt": zod.string().nullish()
})


/**
 * @summary Delete a message for myself
 */
export const RemoveMessageParams = zod.object({
  "conversationId": zod.coerce.string(),
  "messageId": zod.coerce.string()
})


/**
 * @summary Delete a message for everyone
 */
export const RemoveMessageForAllParams = zod.object({
  "conversationId": zod.coerce.string(),
  "messageId": zod.coerce.string()
})


/**
 * @summary Mark messages in conversation as read
 */
export const MarkReadParams = zod.object({
  "conversationId": zod.coerce.string()
})


/**
 * @summary Upload an encrypted file attachment
 */
export const UploadFileBody = zod.object({
  "filename": zod.string(),
  "mimeType": zod.string(),
  "sizeBytes": zod.number(),
  "encryptedData": zod.string().describe('Base64 encoded encrypted file data')
})


/**
 * @summary Update user profile (avatar)
 */
export const UpdateProfileBody = zod.object({
  "theme": zod.enum(['dark', 'light']).optional()
})

export const updateProfileResponseThemeDefault = `dark`;

export const UpdateProfileResponse = zod.object({
  "id": zod.string(),
  "userId": zod.string().describe('Human-readable ID like END-48291'),
  "avatarUrl": zod.string().nullish(),
  "theme": zod.enum(['dark', 'light']).default(updateProfileResponseThemeDefault),
  "storageUsedBytes": zod.number().optional(),
  "createdAt": zod.string()
})


/**
 * @summary Upload avatar image (base64)
 */
export const UploadAvatarBody = zod.object({
  "dataUrl": zod.string().describe('Base64 data URL of avatar image')
})

export const UploadAvatarResponse = zod.object({
  "avatarUrl": zod.string()
})


/**
 * @summary Permanently delete account
 */
export const DeleteAccountBody = zod.object({
  "password": zod.string()
})


